# Generated by Django 4.1.3 on 2022-11-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
